name: "Test: Haskell"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dep install
      run: |
        sudo apt install cabal-install ghc haskell-stack
        cabal update
        stack init
        stack --resolver lts-18 build
    - name: make haskell
      run: make haskell
