name: "Test: Haskell"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: go install
      run: sudo apt install cabal-install
    - name: make haskell
      run: make haskell
